name: Workflow with Email Identifier

on:
  # Runs when manually triggered
  workflow_dispatch:
  # Also runs on push to main branch
  push:
    branches: [ main ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: 24f2001647@ds.study.iitm.ac.in
        run: echo "Hello, world!"
        
      - name: 5-10-2025
        run: date
